### PR TITLE
Update for new data and geos

### PR DESCRIPTION
**Pull request by rpitingolo**
@NeighborhoodInfoDC/review this is supposed to go with issue 29. I made a mistake naming the branch and didn't know how to change it.

I updated the address points macro to include some of our new standard geographies. I also downloaded an new address points file, figuring it would be good to do the update while I had the branch open. Let me know if it looks OK to finalize.

### CODE REVIEW

**Comment by ptatian** [comment]
@rpitingolo I will take a look.

**Comment by rpitingolo** [comment]
@ptatian thanks. I updated Address_points_view.sas. Did you also review the geocode macro that I updated? 

For the Address_points_xy, confirming that I don't have to update the SAS program, but rather the file that feeds into it?

**Comment by rpitingolo** [comment]
@ptatian this is ready for another review. In addition to Address_points_view.sas it looked like I also had to update Geocode_94_dc_source.sas and Geocode_dc_source.sas. 

Hopefully we can wrap this up soon because this is needed to get the Stanton Commons geography on to the new vital stats data. 

cc: @maggiesu0725

**Comment by ptatian** [comment]
Sorry, @rpitingolo. I'll look at the rest of it now.

**Comment by rpitingolo** [comment]
Sounds good. I know yipeng has a deadline tomorrow so just trying to be mindful of that.
________________________________

**Comment by ptatian** [comment]
@rpitingolo So we aren't following the "rule" that we just established that an issue ends with a batch submit. The challenge is that it's hard to test **Geocode_94_dc_source.sas** without having first run the new address points, and hard to test the geocoding macro until the source files are updated. 

That said, the changes you made seem OK to me, so I'd suggest just merging this and then batch submitting the address points and geocode source programs, checking all carefully to make sure they ran OK. 

You can then batch submit **Prog\Geocode_test.sas** to test the macro. The test program results should be consistent with the **Prog\Geocode_test_94 - Ref.html** file on L:, except that the new geo vars should now appear in the output.

**Comment by rpitingolo** [comment]
@ptatian yes, sorry about that. This turned out to have more steps than I realized when I started. If there are any issues I'll open a new bugfix issue to correct.

**Pull request merged**
