### PR TITLE
Create Address_points_2022_07.sas

### PR DESCRIPTION
**Pull request by eburton9**
@rpitingolo

### CODE REVIEW

**Comment by rpitingolo** [comment]
@eburton9 OK I think I fixed the big problem. Can you re-run and note and errors or warnings you see in the log?

**Comment by eburton9** [comment]
@rpitingolo warnings iclude invalid neighborhood cluster and invalid voter precinct.. I also completely accidentally merged the pull request...

**Comment by rpitingolo** [comment]
@eburton9 ok I'll reopen the branch and look into the warnings

**Comment by ptatian** [comment]
@rpitingolo @eburton9 I just wanted to confirm that this is done and there were no additional issues to address?

**Comment by rpitingolo** [comment]
@ptatian yep. This one is fully complete.

**Pull request merged**
