### PR TITLE
Add new geos to geocoding file

### PR DESCRIPTION
**Pull request by rpitingolo**
@ptatian can you please review this program? I updated to add the 2020 census geographies and ward2022.

### CODE REVIEW

**Comment by ptatian** [comment]
Thanks, @rpitingolo. I'll take a look.

**Comment by rpitingolo** [comment]
@ptatian sorry about that. closed now.

**Review by ptatian — APPROVED** [review]
@rpitingolo This all looks good. I changed the location of the list of streets to the default path, which is now our standard practice, and I edited the Geocode macro source code to include the new geo vars. I also updated the **Geocode_test.sas** program, which you should batch submit after merging and updating the geocoding source data to test whether the macro works.

**Comment by ptatian** [comment]
@rpitingolo The other thing I wanted to point out is that these data sets will only work as a geocoding source if someone is running SAS 9.4 or later. If everyone has got 9.4 then that's OK. But if anyone is still using 9.2 or 9.3, then we also need to update the data sets in Geocode_dc_source.sas.

**Comment by rpitingolo** [comment]
@ptatian thank you. I asked Sybil and she said everyone at Urban should be on at least SAS 9.4 M1 by now, and if they aren't they should ask for an upgrade, so I think we are OK to just update this one unless you want to do Geocode_dc_source.sas too just in case.

**Pull request merged**
